# app/config/config.yml
easy_admin:
    entities:
        # change the following to the namespaces of your own entities
        - App\Entity\User
        - App\Entity\Category
        - App\Entity\DeliveryMode
        - App\Entity\PaymentMode
        - App\Entity\OrderPaymentFarmer
        - App\Entity\Product
    site_name: 'LCDV'
